package main

import (
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strings"
)

type AutoGenerated struct {
	Subject string `json:"subject"`
	Links   []struct {
		Rel  string `json:"rel"`
		Href string `json:"href"`
		Type string `json:"type,omitempty"`
	} `json:"links"`
}

func main() {

	http.HandleFunc("/authorize_interaction", func(w http.ResponseWriter, r *http.Request) {
		host := os.Getenv("APP_HOST")
		_ = host
		log.Printf("%v", r.RequestURI)
		w.Write([]byte("OK"))
	})

	http.HandleFunc("/u/", func(w http.ResponseWriter, r *http.Request) {
		host := os.Getenv("APP_HOST")
		_ = host
		log.Printf("%v", r.RequestURI)
		b, _ := ioutil.ReadAll(r.Body)
		log.Printf("%s", b)
		w.Write([]byte("OK"))

	})

	http.HandleFunc("/users/", func(w http.ResponseWriter, r *http.Request) {
		host := os.Getenv("APP_HOST")
		_ = host
		log.Printf("%v", r.RequestURI)
		b, _ := ioutil.ReadAll(r.Body)
		log.Printf("%s", b)
		w.Write([]byte("OK"))
	})

	http.HandleFunc("/.well-known/webfinger", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("%v", r.RequestURI)
		b, _ := ioutil.ReadAll(r.Body)
		log.Printf("%s", b)
		resource := r.URL.Query().Get("resource")
		parts := strings.SplitN(resource, ":", 2)
		_ = parts
		user := parts[1]
		_ = user
		host := os.Getenv("APP_HOST")
		w.Header().Set("Content-Type", "application/jrd+json")
		w.Write([]byte(`{
			"subject": "` + resource + `",
			"links": [
					{
						"rel": "http://ostatus.org/schema/1.0/subscribe",
						"template": "` + host + `/authorize_interaction?uri={uri}"
					  }
				{
					"rel": "self",
					"type": "application/activity+json",
					"href": "` + host + `/users/lempa"
				},
				{
					"rel": "http://webfinger.net/rel/profile-page",
					"type": "text/html",
					"href": "` + host + `/u/lempa"
				}
			]
			}`,
		))
	})
	log.Fatal(http.ListenAndServe(os.Getenv("APP_BIND"), nil))
}
